title: Wavebender GAN
theme: jekyll-theme-dinky
description: Deep architecture for high-quality and controllable speech synthesis through interpretable features and exchangeable neural synthesizers
show_downloads: False
logo: ./images/WavebenderGAN.png
